name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: List directory contents
        run: ls -R
      - name: Install dependencies
        run: |
          cd assignment1
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest

  docker-build-and-run:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd assignment1
          docker build -t ghcr.io/${{ github.repository }}/assignment1:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name my_container ghcr.io/${{ github.repository }}/assignment1:latest

      - name: Check running containers
        run: docker ps

      - name: Output container logs
        run: docker logs my_container
